### ISSUE TITLE
right-justified?

### ISSUE THREAD

**Issue by kk98kk** [timdows/MMM-JsonTable#22]
I would like to right-justify my numbers. Can anyone give me a clue, how to do it. It´s always is left-justified.
![1](https://user-images.githubusercontent.com/88677709/131933640-381fd23f-3b36-4618-872a-0af5586ca0c2.PNG)

**Comment by timdows** [comment]
If you got some knowledge about CSS, this might help you

```css
table > tr > td:nth-child(2) {
  color: blue;
}
```
